services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
    networks:
      default:
      jumpseller:
        aliases:
          - react-sunset-sunrise
    command: npm start

networks:
  jumpseller:
    external: true
    name: sunset-sunrise