services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
    networks:
      - default 
      - sunset-sunrise
    command: npm start

networks:
  sunset-sunrise:
    external: true